export const HOST = "http://3.18.49.30";
export const ENDPOINT_URL = `${HOST}:8000/api`;
export const APP_NAME = "Funny Money";
export const CURRENCIES = [
  { value: "AUD" },
  { value: "BRL" },
  { value: "BGN" },
  { value: "CAD" },
  { value: "CNY" },
  { value: "HRK" },
  { value: "CYP" },
  { value: "CZK" },
  { value: "DKK" },
  { value: "EEK" },
  { value: "EUR" },
  { value: "HKD" },
  { value: "HUF" },
  { value: "ISK" },
  { value: "IDR" },
  { value: "JPY" },
  { value: "KRW" },
  { value: "LVL" },
  { value: "LTL" },
  { value: "MYR" },
  { value: "MTL" },
  { value: "NZD" },
  { value: "NOK" },
  { value: "PHP" },
  { value: "PLN" },
  { value: "RON" },
  { value: "RUB" },
  { value: "SGD" },
  { value: "SKK" },
  { value: "SIT" },
  { value: "ZAR" },
  { value: "SEK" },
  { value: "CHF" },
  { value: "THB" },
  { value: "TRY" },
  { value: "GBP" },
  { value: "USD" }
];
export const SYMBOLS = [
  { value: "XRP" },
  { value: "BTC" },
  { value: "APPLE" },
  { value: "GOLD" },
  { value: "EWT" },
  { value: "GSX" },
  { value: "AIRBNB" },
  { value: "SILVER" }
];
