export const currentUserActionTypes = {
  FETCH_USER_START: "FETCH_USER_START",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAIL: "FETCH_USER_FAIL",
  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",
  SET_RANK: "SET_RANK",
  SET_NEW_PREDICTIONS: "SET_NEW_PREDICTIONS",
  SET_CURRENCY: "SET_CURRENCY",
  SET_ACCURACY: "SET_ACCURACY",
  SET_PAST_PREDICTIONS: "SET_PAST_PREDICTIONS"
};

export const newsActionTypes = {
  FETCH_NEWS_START: "FETCH_NEWS_START",
  FETCH_NEWS_SUCCESS: "FETCH_NEWS_SUCCESS",
  FETCH_NEWS_FAIL: "FETCH_NEWS_FAIL"
};

export const predictionActionTypes = {
  SET_NAME_OR_SYMBOL: "SET_NAME_OR_SYMBOL",
  SET_DATE: "SET_DATE",
  SET_PRICE: "SET_PRICE"
};

export const themeActionTypes = {
  SET_DARK_MODE = "SET_DARK_MODE",
  SET_LIGHT_MODE = "SET_LIGHT_MODE",
};

export const appActionTypes = {};
