export const currentUserActionTypes = {
  SET_FULL_NAME: "SET_FULL_NAME",
  SET_DISPLAY_NAME: "SET_DISPLAY_NAME",
  SET_EMAIL: "SET_EMAIL",
  SET_PASSWORD: "SET_PASSWORD",
  SET_CONFIRM_PASSWORD: "SET_CONFIRM_PASSWORD"
};

export const appActionTypes = {};
